export const MAX_ORDER_LINE_QUANTITY = 99;
export const MAX_DELIVERY_COST = 999.99;
export const MAX_INVENTORY_AUDIT_NOTE_LENGTH = 500;
export const ORDER_CANCELLATION_AUDIT_PREFIX = "Order cancelled: ";
export const MAX_ORDER_CANCELLATION_REASON_LENGTH =
	MAX_INVENTORY_AUDIT_NOTE_LENGTH - ORDER_CANCELLATION_AUDIT_PREFIX.length;
