services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - ./redis-data:/data

  postgres:
    image: postgres:17.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
